apiVersion: apps/v1
kind: Deployment
metadata:
  name: hostpath-exec-deployment
  labels:
    app: pentest
    type: deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pentest
      type: deployment
  template:
    metadata:
      labels:
        app: pentest
        type: deployment
    spec:
      containers:
      - name: hostpath-exec-deployment
        image: beserkerbob/hackingcontainerkubernetes:0.2
        volumeMounts:
        - mountPath: /host
          name: noderoot
        command: [ "sleep", "infinity"]

      #nodeName: k8s-control-plane-node # Force your pod to run on the control-plane node by uncommenting this line and changing to a control-plane node name
      volumes:
      - name: noderoot
        hostPath:
          path: /
      