apiVersion: apps/v1
kind: Deployment
metadata:
  name: hostpid-privileged-exec-deployment
  labels:
    app: pentest
    type: deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pentest
      type: deployment
  template:
    metadata:
      labels:
        app: pentest
        type: deployment
    spec:
      hostPID: true
      containers:
      - name: hostpid-privileged-exec-deployment
        image: beserkerbob/hackingcontainerkubernetes:0.2
        securityContext:
          privileged: true
        command: [ "sleep", "infinity"]

      ##########nodeName:.*
      
