apiVersion: v1
kind: ReplicationController
metadata:
  name: hostnetwork-exec-replicationcontroller
  labels:
    app: pentest
    type: replicationcontroller
spec:
  replicas: 2
  selector:
    app: pentest
    type: replicationcontroller
  template:
    metadata:
      labels:
        app: pentest
        type: replicationcontroller
    spec:
      hostNetwork: true
      containers:
      - name: hostnetwork-exec-replicationcontroller
        image: beserkerbob/hackingcontainerkubernetes:0.2
        command: [ "sleep", "infinity"]

      #nodeName: k8s-control-plane-node # Force your pod to run on the control-plane node by uncommenting this line and changing to a control-plane node name

      